#include <iostream>
using namespace std;
int main(){

cout <<"Enter no:";
int num;
cin>>num;
if (num == 1) cout<<"one"<<endl;
else if (num == 2) cout<<"two"<<endl;
else if (num == 3) cout<<"three"<<endl;
else if (num == 4) cout<<"four"<<endl;
else if (num == 5) cout<<"five"<<endl;
else if (num == 6) cout<<"six"<<endl;
else if (num == 7) cout<<"seven"<<endl;
else if (num == 8) cout<<"eight"<<endl;
else if (num == 9) cout<<"nine"<<endl;
else if (num == 10) cout<<"ten"<<endl;
else if (num == 11) cout<<"eleven"<<endl;
else if (num == 12) cout<<"twelve"<<endl;
else if (num == 13) cout<<"thirteen"<<endl;
else if (num == 14) cout<<"fourteen"<<endl;
else if (num == 15) cout<<"fifteen"<<endl;
else if (num == 16) cout<<"sixteen"<<endl;
else if (num == 17) cout<<"seventeen"<<endl;
else if (num == 18) cout<<"eighteen"<<endl;
else if (num == 19) cout<<"nineteen"<<endl;
else if (num == 20) cout<<"twenty"<<endl;
else if (num == 21) cout<<"twenty one"<<endl;
else if (num == 22) cout<<"twenty two"<<endl;
else if (num == 23) cout<<"twenty three"<<endl;
else if (num == 24) cout<<"twenty four"<<endl;
else if (num == 25) cout<<"twenty five"<<endl;
else if (num == 26) cout<<"twenty six"<<endl;
else if (num == 27) cout<<"twenty seven"<<endl;
else if (num == 28) cout<<"twenty eight"<<endl;
else if (num == 29) cout<<"twenty nine"<<endl;
else if (num == 30) cout<<"thirty"<<endl;
else if (num == 31) cout<<"thirty one"<<endl;
else if (num == 32) cout<<"thirty two"<<endl;
else if (num == 33) cout<<"thirty three"<<endl;
else if (num == 34) cout<<"thirty four"<<endl;
else if (num == 35) cout<<"thirty five"<<endl;
else if (num == 36) cout<<"thirty six"<<endl;
else if (num == 37) cout<<"thirty seven"<<endl;
else if (num == 38) cout<<"thirty eight"<<endl;
else if (num == 39) cout<<"thirty nine"<<endl;
else if (num == 40) cout<<"forty"<<endl;
else if (num == 41) cout<<"forty one"<<endl;
else if (num == 42) cout<<"forty two"<<endl;
else if (num == 43) cout<<"forty three"<<endl;
else if (num == 44) cout<<"forty four"<<endl;
else if (num == 45) cout<<"forty five"<<endl;
else if (num == 46) cout<<"forty six"<<endl;
else if (num == 47) cout<<"forty seven"<<endl;
else if (num == 48) cout<<"forty eight"<<endl;
else if (num == 49) cout<<"forty nine"<<endl;
else if (num == 50) cout<<"fifty"<<endl;
else if (num == 51) cout<<"fifty one"<<endl;
else if (num == 52) cout<<"fifty two"<<endl;
else if (num == 53) cout<<"fifty three"<<endl;
else if (num == 54) cout<<"fifty four"<<endl;
else if (num == 55) cout<<"fifty five"<<endl;
else if (num == 56) cout<<"fifty six"<<endl;
else if (num == 57) cout<<"fifty seven"<<endl;
else if (num == 58) cout<<"fifty eight"<<endl;
else if (num == 59) cout<<"fifty nine"<<endl;
else if (num == 60) cout<<"sixty"<<endl;
else if (num == 61) cout<<"sixty one"<<endl;
else if (num == 62) cout<<"sixty two"<<endl;
else if (num == 63) cout<<"sixty three"<<endl;
else if (num == 64) cout<<"sixty four"<<endl;
else if (num == 65) cout<<"sixty five"<<endl;
else if (num == 66) cout<<"sixty six"<<endl;
else if (num == 67) cout<<"sixty seven"<<endl;
else if (num == 68) cout<<"sixty eight"<<endl;
else if (num == 69) cout<<"sixty nine"<<endl;
else if (num == 70) cout<<"seventy"<<endl;
else if (num == 71) cout<<"seventy one"<<endl;
else if (num == 72) cout<<"seventy two"<<endl;
else if (num == 73) cout<<"seventy three"<<endl;
else if (num == 74) cout<<"seventy four"<<endl;
else if (num == 75) cout<<"seventy five"<<endl;
else if (num == 76) cout<<"seventy six"<<endl;
else if (num == 77) cout<<"seventy seven"<<endl;
else if (num == 78) cout<<"seventy eight"<<endl;
else if (num == 79) cout<<"seventy nine"<<endl;
else if (num == 80) cout<<"eighty"<<endl;
else if (num == 81) cout<<"eighty one"<<endl;
else if (num == 82) cout<<"eighty two"<<endl;
else if (num == 83) cout<<"eighty three"<<endl;
else if (num == 84) cout<<"eighty four"<<endl;
else if (num == 85) cout<<"eighty five"<<endl;
else if (num == 86) cout<<"eighty six"<<endl;
else if (num == 87) cout<<"eighty seven"<<endl;
else if (num == 88) cout<<"eighty eight"<<endl;
else if (num == 89) cout<<"eighty nine"<<endl;
else if (num == 90) cout<<"ninety"<<endl;
else if (num == 91) cout<<"ninety one"<<endl;
else if (num == 92) cout<<"ninety two"<<endl;
else if (num == 93) cout<<"ninety three"<<endl;
else if (num == 94) cout<<"ninety four"<<endl;
else if (num == 95) cout<<"ninety five"<<endl;
else if (num == 96) cout<<"ninety six"<<endl;
else if (num == 97) cout<<"ninety seven"<<endl;
else if (num == 98) cout<<"ninety eight"<<endl;
else if (num == 99) cout<<"ninety nine"<<endl;
else if (num == 100) cout<<"one hundred"<<endl;
}