# include <iostream>
using namespace std;
int main()
{
cout<<"enter number1:"<<endl;
int number1;
cin>>number1;
cout<<"enter number2:"<<endl;
int number2;
cin>>number2;
cout<<"enter number3:"<<endl;
int number3;
cin>>number3;
cout<<"enter number4:"<<endl;
int number4;
cin>>number4;
cout<<"enter number5:"<<endl;
int number5;
cin>>number5;
cout<<"enter number6:"<<endl;
int number6;
cin>>number6;
cout<<"enter number7:"<<endl;
int number7;
cin>>number7;
cout<<"enter number8:"<<endl;
int number8;
cin>>number8;
cout<<"enter number9:"<<endl;
int number9;
cin>>number9;
cout<<"enter number10:"<<endl;
int number10;
cin>>number10;
cout<<"enter number11:"<<endl;
int number11;
cin>>number11;
cout<<"enter number12:"<<endl;
int number12;
cin>>number12;
cout<<"enter number13:"<<endl;
int number13;
cin>>number13;
cout<<"enter number14:"<<endl;
int number14;
cin>>number14;
cout<<"enter number15:"<<endl;
int number15;
cin>>number15;
int add,multiplies,subtract,sum;
add=number1+number2+number3+number4+number5;
multiplies=number6*number7*number8*number9*number10;
subtract=number11-number12-number13-number14-number15;
sum=(add+multiplies)-subtract;
cout<<"number1:"<<number1<<endl;
cout<<"number2:"<<number2<<endl;
cout<<"number3:"<<number3<<endl;
cout<<"number4:"<<number4<<endl;
cout<<"number5:"<<number5<<endl;
cout<<"number6:"<<number6<<endl;
cout<<"number7:"<<number7<<endl;
cout<<"number8:"<<number8<<endl;
cout<<"number9:"<<number9<<endl;
cout<<"number10:"<<number10<<endl;
cout<<"number11:"<<number11<<endl;
cout<<"number12:"<<number12<<endl;
cout<<"number13:"<<number13<<endl;
cout<<"number14:"<<number14<<endl;
cout<<"number15:"<<number15<<endl;
cout<<"THE FINAL RESULT IS:"<<sum<<endl;
}